name: Deploy Docker Container to EC2 Instances

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key for EC2 access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: SSH into EC2 (Instance 1) and deploy container
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS_PROD_1 }} << 'EOF'
          sudo dnf update -y
          if ! command -v docker &> /dev/null; then
            sudo dnf install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          if ! sudo systemctl is-active --quiet docker; then
            sudo systemctl start docker
          fi
          sudo docker stop languaje-python-app || true
          sudo docker rm languaje-python-app || true
          sudo docker pull kevinseya/languaje-python-app:latest
          sudo docker run -d --name languaje-python-app -p 80:80 kevinseya/languaje-python-app:latest
        EOF

    - name: SSH into EC2 (Instance 2) and deploy container
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS_PROD_2 }} << 'EOF'
          sudo dnf update -y
          if ! command -v docker &> /dev/null; then
            sudo dnf install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          if ! sudo systemctl is-active --quiet docker; then
            sudo systemctl start docker
          fi
          sudo docker stop languaje-python-app || true
          sudo docker rm languaje-python-app || true
          sudo docker pull kevinseya/languaje-python-app:latest
          sudo docker run -d --name languaje-python-app -p 80:80 kevinseya/languaje-python-app:latest
        EOF

    - name: SSH into EC2 (Instance 3) and deploy container
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS_PROD_3 }} << 'EOF'
          sudo dnf update -y
          if ! command -v docker &> /dev/null; then
            sudo dnf install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          if ! sudo systemctl is-active --quiet docker; then
            sudo systemctl start docker
          fi
          sudo docker stop languaje-python-app || true
          sudo docker rm languaje-python-app || true
          sudo docker pull kevinseya/languaje-python-app:latest
          sudo docker run -d --name languaje-python-app -p 80:80 kevinseya/languaje-python-app:latest
        EOF

    - name: SSH into EC2 (Instance 4) and deploy container
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS_PROD_4 }} << 'EOF'
          sudo dnf update -y
          if ! command -v docker &> /dev/null; then
            sudo dnf install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          if ! sudo systemctl is-active --quiet docker; then
            sudo systemctl start docker
          fi
          sudo docker stop languaje-python-app || true
          sudo docker rm languaje-python-app || true
          sudo docker pull kevinseya/languaje-python-app:latest
          sudo docker run -d --name languaje-python-app -p 80:80 kevinseya/languaje-python-app:latest
        EOF
